const ChartConfigTypes = {
    SET_STATE_SELECTION : "SET_STATE_SELECTION",
    SET_DATE_RANGE_SELECTION : "SET_DATE_RANGE_SELECTION",
    SET_FIELD_SELECTION : "SET_FIELD_SELECTION",
    SET_COVID19_DATA : "SET_COVID19_DATA",
    SET_STATE_HISTORY_DATA: "SET_STATE_HISTORY_DATA",
    SET_YEAR_SELECTION : "SET_YEAR_SELECTION"
};

export default ChartConfigTypes;